### ISSUE TITLE
Can integrate capsolver.com?

### ISSUE THREAD

**Issue by Xeeeno** [openHacking/bypass-captcha#1]
Hey, it's possible that you integrate [capsolver.com](https://www.capsolver.com/), they have the cheapest and fastest captcha solution of the whole market.
They can solve hcaptcha, recaptcha, amazon waf captcha, turnstile, kasada, akamai, funcaptcha, datadome captcha, geetest etc...
Also you can check their documentation here: https://docs.capsolver.com/

**Comment by openHacking** [comment]
> Hey, it's possible that you integrate [capsolver.com](https://www.capsolver.com/), they have the cheapest and fastest captcha solution of the whole market. They can solve hcaptcha, recaptcha, amazon waf captcha, turnstile, kasada, akamai, funcaptcha, datadome captcha, geetest etc... Also you can check their documentation here: https://docs.capsolver.com/

Hello, this is the code repository associated with a sponsored article, the article address is: https://lwebapp.com/en/post/bypass-captcha

If you have similar business needs, please contact openHacking@126.com
